<?php

namespace App\Imports;

use App\Models\Product;
use App\Models\ProductImage;
use App\Models\ProductTag;
use App\Models\ProductSpecification;
use App\Models\Variant;
use App\Models\VariantImage;
use App\Models\Category;
use App\Models\Brand;
use App\Models\Tag;
use App\Models\Color;
use App\Models\Size;
use App\Models\StockAdjustment;
use Illuminate\Support\Collection;
use Maatwebsite\Excel\Concerns\ToCollection;
use Maatwebsite\Excel\Concerns\WithHeadingRow;
use Maatwebsite\Excel\Concerns\WithMultipleSheets;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Validator;
use App\Exceptions\ImportException;
use Exception;

class ProductImport implements ToCollection, WithHeadingRow, WithMultipleSheets
{
    protected $images;
    protected $validationOnly = false;
    protected $importingBarcodes = []; // Track barcodes being imported in this batch
    protected $deferredVariants = []; // Queue for variants that need processing after products are created

    protected $results = [
        'successful' => 0,
        'failed' => 0,
        'total_processed' => 0,
        'errors' => []
    ];

    protected $validationResults = [
        'total_rows' => 0,
        'valid_rows' => 0,
        'invalid_rows' => 0,
        'errors' => [],
        'warnings' => [],
        'validation_data' => []
    ];

    protected $validationData = [];

    public function __construct($images = [])
    {
        $this->images = $images;
    }

    public function setValidationOnly($validationOnly)
    {
        $this->validationOnly = $validationOnly;
    }

    public function getResults()
    {
        return $this->results;
    }

    public function getValidationResults()
    {
        return $this->validationResults;
    }

    public function getValidationData()
    {
        return $this->validationData;
    }

    // Helper accessors/mutators for sheet handlers
    public function isValidationOnly(): bool
    {
        return (bool) $this->validationOnly;
    }

    public function pushValidationError(array $entry): void
    {
        $this->validationResults['errors'][] = $entry;
    }

    public function pushValidationData(array $entry): void
    {
        $this->validationData[] = $entry;
    }

    public function pushResultError(array $entry): void
    {
        $this->results['errors'][] = $entry;
    }

    public function getImages(): array
    {
        return $this->images ?? [];
    }

    public function getImportingBarcodes(): array
    {
        return $this->importingBarcodes;
    }

    public function getDeferredVariants(): array
    {
        return $this->deferredVariants;
    }

    public function clearDeferredVariants(): void
    {
        $this->deferredVariants = [];
    }

    public function addDeferredVariant($row): void
    {
        $this->deferredVariants[] = $row;
    }

    public function processVariantDirect($row, $product): void
    {
        // This is accessible to ProductVariantsSheet for handling deferred variants
        $this->createOrUpdateVariantInternal($row, $product);
    }

    public function headingRow(): int
    {
        return 1;
    }

    /**
     * Implement WithMultipleSheets to specify which sheets to process
     */
    public function sheets(): array
    {
        return [
            'Products' => $this,
            'Specifications' => new ProductSpecificationsSheet($this),
            'Variants' => new ProductVariantsSheet($this),
        ];
    }

    public function collection(Collection $rows)
    {
        // First pass: collect all barcodes being imported (for new products)
        // Include both explicit barcodes and placeholders for auto-generated ones
        $hasAutoGeneratedProducts = false;
        foreach ($rows as $index => $row) {
            if ($this->isEmptyRow($row)) {
                continue;
            }
            
            $barcode = $row['barcode'] ?? null;
            if ($barcode) {
                $this->importingBarcodes[] = (string)$barcode;
            } else {
                // Product will get auto-generated barcode
                $hasAutoGeneratedProducts = true;
            }
        }
        
        // Remove duplicates
        $this->importingBarcodes = array_unique($this->importingBarcodes);
        
        // Mark that we have auto-generated barcodes (used later for relaxing some validations)
        if ($hasAutoGeneratedProducts) {
            $this->importingBarcodes[] = '__AUTO_GENERATED__';
        }
        
        // Second pass: validate and process rows
        foreach ($rows as $index => $row) {
            $excelRowNumber = $index + 2;

            if ($this->isEmptyRow($row)) {
                continue;
            }

            $this->validationResults['total_rows']++;
            $this->results['total_processed']++;

            try {
                $validator = $this->validateRow($row, $excelRowNumber);

                if ($validator->fails()) {
                    $errors = $validator->errors()->all();

                    if ($this->validationOnly) {
                        $this->validationResults['invalid_rows']++;
                        $this->validationResults['errors'][] = [
                            'row' => $excelRowNumber,
                            'barcode' => $row['barcode'] ?? 'N/A',
                            'errors' => $errors
                        ];

                        $this->storeValidationData($row, false, $errors);
                    } else {
                        $this->results['failed']++;
                        $this->results['errors'][] = [
                            'row' => $excelRowNumber,
                            'barcode' => $row['barcode'] ?? 'N/A',
                            'errors' => $errors
                        ];
                    }
                    continue;
                }

                if ($this->validationOnly) {
                    $this->validationResults['valid_rows']++;
                    $warnings = $this->getWarnings($row);
                    if (!empty($warnings)) {
                        $this->validationResults['warnings'][] = [
                            'row' => $excelRowNumber,
                            'barcode' => $row['barcode'] ?? 'N/A',
                            'warnings' => $warnings
                        ];
                    }

                    $this->storeValidationData($row, true, [], $warnings);
                } else {
                    $this->processProduct($row);
                    $this->results['successful']++;
                }
            } catch (Exception $e) {
                if ($this->validationOnly) {
                    $this->validationResults['invalid_rows']++;
                    $this->validationResults['errors'][] = [
                        'row' => $excelRowNumber,
                        'barcode' => $row['barcode'] ?? 'N/A',
                        'errors' => [$e->getMessage()]
                    ];
                    $this->storeValidationData($row, false, [$e->getMessage()]);
                } else {
                    $this->results['failed']++;
                    $this->results['errors'][] = [
                        'row' => $excelRowNumber,
                        'barcode' => $row['barcode'] ?? 'N/A',
                        'errors' => [$e->getMessage()]
                    ];
                }
            }
        }

        if ($this->validationOnly) {
            $this->validationResults['validation_data'] = $this->validationData;
        }
    }

    /**
     * Store validation data for compatibility analysis
     */
    private function storeValidationData($row, $isValid, $errors = [], $warnings = [])
    {
        $barcode = $row['barcode'] ?? 'N/A';

        $this->validationData[] = [
            'barcode' => $barcode,
            'row_data' => $row->toArray(),
            'is_valid' => $isValid,
            'errors' => $errors,
            'warnings' => $warnings
        ];
    }

    /**
     * Map a validated row into attributes for Product::create/update.
     * Includes warranty so it is imported/exported consistently.
     */
    private function mapRowToProductData(array $row): array
    {
        $data = [
            'barcode' => $row['barcode'] ?? null,
            'price' => $row['price'] ?? null,
            'discount' => $row['discount'] ?? 0,
            'min_order_quantity' => $row['min_order_quantity'] ?? 1,
            'max_order_quantity' => $row['max_order_quantity'] ?? null,
        ];

        if (array_key_exists('warranty', $row)) {
            $data['warranty'] = $row['warranty'] ?? null;
        }

        // Keep any other attribute-building logic that already exists
        return $data;
    }

    private function isEmptyRow($row)
    {
        $essentialFields = [
            'barcode',
            'category',
            'brand',
            'availability_status',
            'price',
            'min_order_quantity'
        ];

        foreach ($essentialFields as $field) {
            if (!empty($row[$field]) && trim($row[$field]) !== '') {
                return false;
            }
        }

        $locales = config('app.locales', ['en']);
        foreach ($locales as $locale) {
            $nameField = "name_{$locale}";
            if (!empty($row[$nameField]) && trim($row[$nameField]) !== '') {
                return false;
            }
        }

        return true;
    }


    private function validateRow($row, $rowNumber)
    {
        $locales = config('app.locales', ['en']);

        if (isset($row['barcode'])) {
            $row['barcode'] = (string)$row['barcode'];
        }

        $localizedRules = [];
        foreach ($locales as $locale) {
            $localizedRules["name_{$locale}"] = 'required|string|max:191';
            $localizedRules["short_description_{$locale}"] = 'required|string|max:191';
            $localizedRules["description_{$locale}"] = 'required|string';
            $localizedRules["specifications_{$locale}"] = 'nullable|string';
        }

        $rules = array_merge([
            'barcode' => 'nullable|string',
            'category' => 'required|string',
            'brand' => 'required|string|exists:brands,name',
            'availability_status' => 'required|in:Available,Coming Soon,Discontinued,Pre Order',
            'price' => 'required|numeric|min:0',
            'discount' => 'nullable|integer|min:0|max:100',
            'min_order_quantity' => 'required|integer|min:1',
            'max_order_quantity' => 'nullable|integer|min:0',
            'tags' => 'nullable|string',
        ], $localizedRules);

        $validator = Validator::make($row->toArray(), $rules);

        $validator->after(function ($validator) use ($row, $rowNumber) {
            $minOrder = (int)($row['min_order_quantity'] ?? 0);
            $maxOrder = isset($row['max_order_quantity']) && $row['max_order_quantity'] !== ''
                ? (int)$row['max_order_quantity']
                : null;

            if ($maxOrder !== null && $maxOrder > 0 && $maxOrder <= $minOrder) {
                $validator->errors()->add('max_order_quantity', 'Max order quantity must be greater than min order quantity when specified.');
            }

            if (!empty($row['tags'])) {
                $tagIds = array_filter(array_map('trim', explode(',', $row['tags'])));
                foreach ($tagIds as $tagId) {
                    if (!is_numeric($tagId) || !Tag::where('id', $tagId)->exists()) {
                        $validator->errors()->add('tags', "Invalid tag ID: {$tagId}. Tag does not exist.");
                        break;
                    }
                }
            }

            if (!empty($row['colors'])) {
                $colorIds = array_filter(array_map('trim', explode(',', $row['colors'])));
                $uniqueColors = array_unique($colorIds);

                if (count($colorIds) !== count($uniqueColors)) {
                    $validator->errors()->add('colors', 'Duplicate colors found in variants.');
                }

                foreach ($colorIds as $colorId) {
                    if (!is_numeric($colorId) || !Color::where('id', $colorId)->exists()) {
                        $validator->errors()->add('colors', "Invalid color ID: {$colorId}. Color does not exist.");
                        break;
                    }
                }

                $barcode = $row['barcode'] ?? null;
                if ($barcode) {
                    $existingProduct = Product::where('barcode', $barcode)->first();
                    if ($existingProduct) {
                        $existingVariants = Variant::where('product_id', $existingProduct->id)
                            ->whereIn('color_id', $colorIds)
                            ->pluck('color_id')
                            ->toArray();

                        if (!empty($existingVariants)) {
                            $duplicateColors = Color::whereIn('id', $existingVariants)->pluck('name')->toArray();
                            $validator->errors()->add('colors', "Variants with colors already exist: " . implode(', ', $duplicateColors));
                        }
                    }
                }
            }

            if (!empty($row['category'])) {
                $categoryExists = Category::where(function ($query) use ($row) {
                    foreach (config('app.locales', ['en']) as $locale) {
                        $query->orWhere("name->{$locale}", $row['category']);
                    }
                })->exists();

                if (!$categoryExists) {
                    $validator->errors()->add('category', "Category '{$row['category']}' does not exist in any locale.");
                }
            }

            if (!empty($row['brand']) && !Brand::where('name', $row['brand'])->exists()) {
                $validator->errors()->add('brand', "Brand '{$row['brand']}' does not exist.");
            }

            foreach (config('app.locales', ['en']) as $locale) {
                $nameField = "name_{$locale}";
                if (!empty($row[$nameField])) {
                    $existingProduct = Product::where("name->{$locale}", $row[$nameField])->first();
                    if ($existingProduct) {
                        $barcode = $row['barcode'] ?? null;
                        if (!$barcode || $existingProduct->barcode !== $barcode) {
                            $validator->errors()->add($nameField, "Product name '{$row[$nameField]}' for locale {$locale} already exists.");
                        }
                    }
                }
            }

            $barcode = $row['barcode'] ?? null;
            if ($barcode) {
                $existingProduct = Product::where('barcode', $barcode)->first();
            }

            $locales = config('app.locales', ['en']);
            foreach ($locales as $locale) {
                $specField = "specifications_{$locale}";
                $specValue = $row[$specField] ?? '';

                if (!empty($specValue)) {
                    $specItems = array_filter(array_map('trim', explode(',', $specValue)));
                    if (empty($specItems)) {
                        $validator->errors()->add($specField, "Specifications for {$locale} are in invalid format.");
                    }
                }
            }

            // Validate images for new products when ZIP is provided
            if (!empty($this->images)) {
                $barcode = $row['barcode'] ?? null;
                
                if ($barcode) {
                    // For explicit barcodes
                    $existingProduct = Product::where('barcode', $barcode)->first();
                    // Require images for new products
                    if (!$existingProduct && (!isset($this->images[$barcode]) || empty($this->images[$barcode]))) {
                        $validator->errors()->add('barcode', "No images found for barcode '{$barcode}' in the ZIP file. New products require at least one image.");
                    }
                } else {
                    // For auto-generated barcodes: cannot validate specific barcode before it's generated
                    // Images will be validated during import when barcode is known
                }
            } else {
                // No images provided in ZIP at all - check if any new products exist
                $barcode = $row['barcode'] ?? null;
                if ($barcode) {
                    $existingProduct = Product::where('barcode', $barcode)->first();
                    if (!$existingProduct) {
                        $validator->errors()->add('barcode', "New product with barcode '{$barcode}' requires a ZIP file with images. No ZIP file was provided.");
                    }
                }
            }

            $price = $row['price'] ?? 0;
            $discount = $row['discount'] ?? 0;
            if ($discount > 0 && $price <= 0) {
                $validator->errors()->add('price', 'Cannot apply discount when price is zero or negative.');
            }

            if ($minOrder > 1000) {
                $validator->errors()->add('min_order_quantity', 'Min order quantity cannot exceed 1000.');
            }

            if ($maxOrder !== null && $maxOrder > 10000) {
                $validator->errors()->add('max_order_quantity', 'Max order quantity cannot exceed 10000.');
            }
        });

        return $validator;
    }

    private function processProduct($row)
    {
        DB::transaction(function () use ($row) {
            $barcode = $row['barcode'] ?: Product::generateBarcode();
            $product = Product::where('barcode', $barcode)->first();

            $category = Category::where(function ($query) use ($row) {
                foreach (config('app.locales', ['en']) as $locale) {
                    $query->orWhere("name->{$locale}", $row['category']);
                }
            })->first();

            $brand = Brand::where('name', $row['brand'])->first();

            if (!$category) {
                throw new ImportException('Category not found: ' . $row['category']);
            }
            if (!$brand) {
                throw new ImportException('Brand not found: ' . $row['brand']);
            }

            $statusMapping = [
                'Available' => 'available',
                'Coming Soon' => 'coming_soon',
                'Discontinued' => 'discontinued',
                'Pre Order' => 'pre_order',
            ];
            $statusId = $statusMapping[$row['availability_status']] ?? 'available';

            $locales = config('app.locales', ['en']);
            $names = $shortDescriptions = $descriptions = [];
            foreach ($locales as $locale) {
                $names[$locale] = $row["name_{$locale}"] ?? '';
                $shortDescriptions[$locale] = $row["short_description_{$locale}"] ?? '';
                $descriptions[$locale] = $row["description_{$locale}"] ?? '';
            }

            $productData = [
                'category_id' => $category->id,
                'brand_id' => $brand->id,
                'availability_status' => $statusId,
                'price' => $row['price'],
                'discount' => $row['discount'] ?? 0,
                'coupon_eligible' => array_key_exists('coupon_eligible', $row)
                    ? (bool) $row['coupon_eligible']
                    : true,
                'min_order_quantity' => $row['min_order_quantity'],
                'max_order_quantity' => isset($row['max_order_quantity']) && $row['max_order_quantity'] !== ''
                    ? $row['max_order_quantity']
                    : null,

                'name' => $names,
                'short_description' => $shortDescriptions,
                'description' => $descriptions,
            ];

            if ($product) {
                // UPDATE existing product
                $product->fill($productData);
                $product->save();

                // Handle tags (delete and recreate)
                ProductTag::where("product_id", $product->id)->delete();
                $this->processTags($product, $row['tags'] ?? '');

                // Handle variants (sync with existing)
                $this->processVariants($product, $row['colors'] ?? '');

                // Handle specifications (delete and recreate) - pass the entire row
                ProductSpecification::where('product_id', $product->id)->delete();
                $this->processSpecifications($product, $row);

                // Handle images (only if new images provided)
                if (isset($this->images[$barcode]) && !empty($this->images[$barcode])) {
                    $this->processImages($product, $barcode);
                }
            } else {
                // CREATE new product
                // Validate that new products have at least one image
                if (!isset($this->images[$barcode]) || empty($this->images[$barcode])) {
                    throw new ImportException("New product with barcode '{$barcode}' requires at least one image in the ZIP file.");
                }
                
                $productData['barcode'] = $barcode;
                $product = new Product($productData);
                $product->slug = null;
                $product->save();

                // Handle tags
                $this->processTags($product, $row['tags'] ?? '');

                // Handle variants
                $this->processVariants($product, $row['colors'] ?? '');

                // Handle specifications - pass the entire row
                $this->processSpecifications($product, $row);

                // Handle images (required for new products)
                $this->processImages($product, $barcode);
            }
        });
    }

    private function getWarnings($row)
    {
        $warnings = [];
        $barcode = $row['barcode'] ?? null;
        $existingProduct = null;
        
        if (!$barcode) {
            $warnings[] = 'Barcode is empty - will be auto-generated';
        } else {
            $existingProduct = Product::where('barcode', $barcode)->first();
            if ($existingProduct) {
                $warnings[] = 'Barcode already exists in database - product will be updated';

                if (!empty($row['colors'])) {
                    $colorIds = array_filter(array_map('trim', explode(',', $row['colors'])));
                    $existingVariants = Variant::where('product_id', $existingProduct->id)
                        ->whereIn('color_id', $colorIds)
                        ->count();

                    if ($existingVariants > 0) {
                        $warnings[] = "{$existingVariants} variant(s) already exist and will be skipped";
                    }
                }
            }
        }

        $locales = config('app.locales', ['en']);
        foreach ($locales as $locale) {
            $descField = "description_{$locale}";
            if (empty($row[$descField] ?? '')) {
                $warnings[] = "Description for {$locale} is empty";
            }
        }

        // Variants are now managed via the Variants sheet. Keeping this warning out to avoid false alarms.

        $price = $row['price'] ?? 0;
        $discount = $row['discount'] ?? 0;
        if ($discount > 50) {
            $warnings[] = 'Discount is over 50% - this might be unusually high';
        }
        if ($price > 10000) {
            $warnings[] = 'Price is unusually high (over 10,000)';
        }

        return $warnings;
    }
    private function processTags($product, $tagsString)
    {
        if (empty($tagsString)) {
            return;
        }

        $tagIds = array_filter(array_map('trim', explode(',', $tagsString)));
        $validTagIds = [];

        foreach ($tagIds as $tagId) {
            if (is_numeric($tagId) && Tag::where('id', $tagId)->exists()) {
                $validTagIds[] = (int)$tagId;
            }
        }

        if (!empty($validTagIds)) {
            $product->tags()->sync($validTagIds);
        }
    }

    private function processVariants($product, $colorsString)
    {
        if (empty($colorsString)) {
            return;
        }

        $colorIds = array_filter(array_map('trim', explode(',', $colorsString)));
        $validColorIds = [];

        // Validate and collect valid color IDs
        foreach ($colorIds as $colorId) {
            if (is_numeric($colorId) && Color::where('id', $colorId)->exists()) {
                $validColorIds[] = (int)$colorId;
            }
        }

        if (empty($validColorIds)) {
            return;
        }

        // Get existing variants to avoid duplicates
        $existingVariants = Variant::where('product_id', $product->id)->get();
        $existingColorIds = $existingVariants->pluck('color_id')->toArray();

        // Create only new variants that don't exist
        foreach ($validColorIds as $colorId) {
            if (!in_array($colorId, $existingColorIds)) {
                Variant::create([
                    'product_id' => $product->id,
                    'color_id' => $colorId,
                    'sku' => Variant::generateSku($product, $colorId),
                ]);
            }
        }

        // Optional: Remove variants that are no longer in the import
        // $variantsToRemove = $existingVariants->whereNotIn('color_id', $validColorIds);
        // foreach ($variantsToRemove as $variant) {
        //     $variant->delete();
        // }
    }

    private function processSpecifications($product, $row)
    {
        $locales = config('app.locales', ['en']);

        // Get specifications for the first locale to determine how many items we have
        $firstLocale = $locales[0];
        $firstSpecField = "specifications_{$firstLocale}";
        $firstSpecValue = $row[$firstSpecField] ?? '';

        if (empty($firstSpecValue)) {
            return;
        }

        // Split specifications by comma
        $specItems = array_filter(array_map('trim', explode(',', $firstSpecValue)));

        foreach ($specItems as $index => $specItem) {
            $specificationsData = [];

            // Build multilingual data for this specification item
            foreach ($locales as $locale) {
                $specField = "specifications_{$locale}";
                $specValue = $row[$specField] ?? '';

                if (!empty($specValue)) {
                    // Get the corresponding part for this locale
                    $localeSpecItems = array_filter(array_map('trim', explode(',', $specValue)));
                    $specificationsData[$locale] = $localeSpecItems[$index] ?? $specItem;
                } else {
                    $specificationsData[$locale] = $specItem;
                }
            }

            if (!empty($specificationsData)) {
                ProductSpecification::create([
                    'product_id' => $product->id,
                    'description' => $specificationsData,
                ]);
            }
        }
    }

    private function processImages($product, $barcode)
    {
        if (!array_key_exists($barcode, $this->images)) {
            return;
        }

        // If the barcode exists but has no images, remove existing images
        if (empty($this->images[$barcode])) {
            $existingImages = $product->images()->get();
            foreach ($existingImages as $image) {
                $storedPath = $image->getRawOriginal('image') ?? $image->image;
                $imagePath = storage_path('app/public/' . $storedPath);
                if (file_exists($imagePath)) {
                    unlink($imagePath);
                }
                $image->delete();
            }
            return;
        }

        // Get existing image hashes to detect duplicates
        $existingImages = $product->images()->get();
        $existingImageHashes = [];
        
        foreach ($existingImages as $image) {
            $storedPath = $image->getRawOriginal('image') ?? $image->image;
            $imagePath = storage_path('app/public/' . $storedPath);
            if (file_exists($imagePath)) {
                $existingImageHashes[$storedPath] = md5_file($imagePath);
            }
        }

        $newImages = [];
        $imagesToDelete = [];
        $arrangement = 1;

        // Process new images
        foreach ($this->images[$barcode] as $imageData) {
            try {
                $tempPath = $imageData['path'];
                
                // Check if file exists
                if (!file_exists($tempPath)) {
                    continue;
                }

                // Calculate hash of new image
                $newImageHash = md5_file($tempPath);
                
                // Check if this image already exists (by hash)
                $isDuplicate = false;
                foreach ($existingImageHashes as $existingPath => $existingHash) {
                    if ($existingHash === $newImageHash) {
                        $isDuplicate = true;
                        $newImages[] = $existingPath;
                        break;
                    }
                }

                // If not a duplicate, store the new image
                if (!$isDuplicate) {
                    $imagePath = $this->storeImage($tempPath, $product->id);
                    $newImages[] = $imagePath;

                    ProductImage::create([
                        'product_id' => $product->id,
                        'image' => $imagePath,
                        'arrangement' => $arrangement,
                        'is_active' => true,
                    ]);

                }

                $arrangement++;
            } catch (Exception $e) {
                // Continue with next image instead of throwing
            }
        }

        // Delete images that were not in the new import
        foreach ($existingImages as $image) {
            $storedPath = $image->getRawOriginal('image') ?? $image->image;
            if (!in_array($storedPath, $newImages)) {
                $imagePath = storage_path('app/public/' . $storedPath);
                if (file_exists($imagePath)) {
                    unlink($imagePath);
                }
                $image->delete();
            }
        }
    }

    /**
     * Store product image from an extracted ZIP temp path.
     *
     * NOTE: The source-of-truth storage implementation lives on the model
     * (see ProductImage::storeImageFromPath). This wrapper exists only to
     * keep import code readable and avoid duplicating filesystem logic here.
     */
    private function storeImage($tempPath, $productId)
    {
        if (!file_exists($tempPath)) {
            throw new ImportException("Image file not found: {$tempPath}");
        }

        return ProductImage::storeImageFromPath($tempPath, $productId);
    }

    public function findColorByName(string $name): ?int
    {
        if ($name === '') return null;
        $locales = config('app.locales', ['en']);
        foreach ($locales as $locale) {
            $color = Color::where("name->{$locale}", $name)->first();
            if ($color) return $color->id;
        }
        // Fallback: try case-insensitive match on translatedName
        $color = Color::all()->first(function ($c) use ($name) {
            app()->setLocale(config('app.locale', 'en'));
            return strcasecmp($c->translatedName, $name) === 0;
        });
        return $color?->id;
    }

    public function findSizeByName(string $name): ?int
    {
        if ($name === '') return null;
        $locales = config('app.locales', ['en']);
        foreach ($locales as $locale) {
            $size = Size::where("name->{$locale}", $name)->first();
            if ($size) return $size->id;
        }
        $size = Size::all()->first(function ($s) use ($name) {
            app()->setLocale(config('app.locale', 'en'));
            return strcasecmp($s->translatedName, $name) === 0;
        });
        return $size?->id;
    }

    private function processVariantImages($variant, $barcode): void
    {
        $images = $this->getImages();
        
        // Check if we have variant images for this barcode
        if (!isset($images[$barcode]['variants']) || !is_array($images[$barcode]['variants'])) {
            // No variant images provided for this barcode; delete any existing images
            $existingImages = $variant->images()->get();
            foreach ($existingImages as $image) {
                $storedPath = $image->getRawOriginal('image') ?? $image->image;
                $imagePath = storage_path('app/public/' . $storedPath);
                if (file_exists($imagePath)) {
                    unlink($imagePath);
                }
                $image->delete();
            }
            return;
        }

        $variantImages = $images[$barcode]['variants'];
        $sku = $variant->sku;

        // Try to find images by SKU first (for existing variants)
        $imagesToProcess = null;
        if (isset($variantImages[$sku]) && !empty($variantImages[$sku])) {
            $imagesToProcess = $variantImages[$sku];
        } else {
            // For new variants, try to match by color/size combination
            $imagesToProcess = $this->findVariantImagesByAttributes($variantImages, $variant);
        }

        // If no images found, return early
        if (empty($imagesToProcess)) {
            // Variant images folder exists but contains no images for this variant; delete existing
            $existingImages = $variant->images()->get();
            foreach ($existingImages as $image) {
                $storedPath = $image->getRawOriginal('image') ?? $image->image;
                $imagePath = storage_path('app/public/' . $storedPath);
                if (file_exists($imagePath)) {
                    unlink($imagePath);
                }
                $image->delete();
            }
            return;
        }

        // Get existing variant image hashes to detect duplicates
        $existingImages = $variant->images()->get();
        $existingImageHashes = [];
        
        foreach ($existingImages as $image) {
            $storedPath = $image->getRawOriginal('image') ?? $image->image;
            $imagePath = storage_path('app/public/' . $storedPath);
            if (file_exists($imagePath)) {
                $existingImageHashes[$storedPath] = md5_file($imagePath);
            }
        }

        $newImages = [];
        $arrangement = 1; // Counter for arrangement order

        // Process new variant images
        foreach ($imagesToProcess as $imageData) {
            try {
                $tempPath = $imageData['path'];
                
                if (!file_exists($tempPath)) {
                    continue;
                }

                // Calculate hash of new image
                $newImageHash = md5_file($tempPath);
                
                // Check if this image already exists (by hash)
                $isDuplicate = false;
                foreach ($existingImageHashes as $existingPath => $existingHash) {
                    if ($existingHash === $newImageHash) {
                        $isDuplicate = true;
                        $newImages[] = $existingPath;
                        break;
                    }
                }

                // If not a duplicate, store the new image
                if (!$isDuplicate) {
                    $imagePath = $this->storeVariantImage($tempPath, $variant->id);
                    $newImages[] = $imagePath;

                    VariantImage::create([
                        'variant_id' => $variant->id,
                        'image' => $imagePath,
                        'arrangement' => $arrangement,
                        'is_active' => true,
                    ]);

                }
                
                $arrangement++;
            } catch (Exception $e) {
            }
        }

        // Delete variant images that were not in the new import
        foreach ($existingImages as $image) {
            $storedPath = $image->getRawOriginal('image') ?? $image->image;
            if (!in_array($storedPath, $newImages)) {
                $imagePath = storage_path('app/public/' . $storedPath);
                if (file_exists($imagePath)) {
                    unlink($imagePath);
                }
                $image->delete();
            }
        }
    }

    private function storeVariantImage($tempPath, $variantId): string
    {
        if (!file_exists($tempPath)) {
            throw new ImportException("Variant image file does not exist: {$tempPath}");
        }

        // Source-of-truth is on the model (VariantImage::storeImageFromPath).
        return VariantImage::storeImageFromPath($tempPath, $variantId);
    }

    /**
     * Find variant images by color/size names for new variants
     * Supports folder names: "ColorName", "ColorName-SizeName", or SKU
     */
    private function findVariantImagesByAttributes(array $variantImages, $variant): ?array
    {
        $color = $variant->color;
        $size = $variant->size;
        
        if (!$color) {
            return null;
        }

        // Get color name in default locale
        $defaultLocale = config('app.locale', 'en');
        $colorName = $color->name[$defaultLocale] ?? $color->translatedName ?? '';
        $sizeName = $size ? ($size->name[$defaultLocale] ?? $size->translatedName ?? '') : null;

        // Try different folder name patterns
        $possibleFolderNames = [];
        
        // Pattern 1: "ColorName" only
        $possibleFolderNames[] = $colorName;
        
        // Pattern 2: "ColorName-SizeName"
        if ($sizeName) {
            $possibleFolderNames[] = "{$colorName}-{$sizeName}";
            $possibleFolderNames[] = "{$colorName}_{$sizeName}";
            $possibleFolderNames[] = "{$colorName} {$sizeName}";
        }

        // Try to find matching folder (case-insensitive)
        foreach ($variantImages as $folderName => $images) {
            foreach ($possibleFolderNames as $pattern) {
                if (strcasecmp($folderName, $pattern) === 0) {
                    return $images;
                }
            }
        }

        return null;
    }

    private function createOrUpdateVariant($row, $product): void
    {
        $this->createOrUpdateVariantInternal($row, $product);
    }

    private function createOrUpdateVariantInternal($row, $product): void
    {
        $colorId = null;
        $sizeId = null;

        $colorName = trim((string)($row['color'] ?? ''));
        if ($colorName !== '') {
            $colorId = $this->findColorByName($colorName);
        }

        $sizeName = trim((string)($row['size'] ?? ''));
        if ($sizeName !== '') {
            $sizeId = $this->findSizeByName($sizeName);
        }

        // Price: use absolute price if provided, otherwise use product price
        $variantPrice = null;
        if ($row['price'] !== null && $row['price'] !== '') {
            $variantPrice = (float)$row['price'];
        }

        // Discount: use provided discount or inherit from product
        $discount = null;
        if (isset($row['discount']) && $row['discount'] !== '') {
            $discount = (int)$row['discount'];
        }

        // Find existing variant by product/color/size
        $variantQuery = Variant::where('product_id', $product->id);
        if ($colorId) $variantQuery->where('color_id', $colorId); else $variantQuery->whereNull('color_id');
        if ($sizeId) $variantQuery->where('size_id', $sizeId); else $variantQuery->whereNull('size_id');

        $variant = $variantQuery->first();

        if ($variant) {
            // Update price if provided
            if ($variantPrice !== null) {
                $variant->price = round($variantPrice, 2);
            }
            // Update discount if provided, otherwise keep existing or use product discount
            if ($discount !== null) {
                $variant->discount = $discount;
            } else {
                // If no discount provided and variant has no discount, inherit from product
                if ($variant->discount === null) {
                    $variant->discount = $product->discount;
                }
            }
            $variant->save();
        } else {
       
            $variant = new Variant([
                'product_id' => $product->id,
                'color_id' => $colorId,
                'size_id' => $sizeId,
                'price' => $variantPrice !== null ? round($variantPrice, 2) : $product->price,
                'discount' => $discount !== null ? $discount : $product->discount,
            ]);
            $variant->sku = Variant::generateSku($product, $colorId, $sizeId);
            $variant->save();
      
        }

        // Handle variant images from ZIP
        $this->processVariantImages($variant, $product->barcode);
    }
}

/**
 * Handle the optional "Variants" sheet.
 * This sheet allows adding/updating variants by product barcode with optional color, size, and price delta.
 */
class ProductVariantsSheet implements ToCollection, WithHeadingRow
{
    private ProductImport $parent;

    public function __construct(ProductImport $parent)
    {
        $this->parent = $parent;
    }

    public function headingRow(): int
    {
        return 1;
    }

    public function collection(Collection $rows)
    {
       
        
        foreach ($rows as $index => $row) {
            $excelRowNumber = $index + 2; // considering header row

            // Skip empty rows (no barcode and no other data)
            if ($this->isEmptyVariantRow($row)) {
                continue;
            }


            try {
                $errors = $this->validateVariantRow($row);

                if (!empty($errors)) {
                    
                    // Report errors in validation mode or during import
                    if ($this->parent->isValidationOnly()) {
                        $this->parent->pushValidationError([
                            'sheet' => 'Variants',
                            'row' => $excelRowNumber,
                            'barcode' => $row['product_barcode'] ?? 'N/A',
                            'errors' => $errors,
                        ]);

                        $this->parent->pushValidationData([
                            'sheet' => 'Variants',
                            'barcode' => $row['product_barcode'] ?? 'N/A',
                            'row_data' => $row->toArray(),
                            'is_valid' => false,
                            'errors' => $errors,
                            'warnings' => []
                        ]);
                    } else {
                        $this->parent->pushResultError([
                            'sheet' => 'Variants',
                            'row' => $excelRowNumber,
                            'barcode' => $row['product_barcode'] ?? 'N/A',
                            'errors' => $errors,
                        ]);
                    }
                    continue;
                }


                if ($this->parent->isValidationOnly()) {
                    // No-op beyond recording valid row for diagnostics
                    $this->parent->pushValidationData([
                        'sheet' => 'Variants',
                        'barcode' => $row['product_barcode'] ?? 'N/A',
                        'row_data' => $row->toArray(),
                        'is_valid' => true,
                        'errors' => [],
                        'warnings' => []
                    ]);
                    continue;
                }

                // Process import for this variant row
                $this->processVariantRow($row);
            } catch (\Exception $e) {
            
                if ($this->parent->isValidationOnly()) {
                    $this->parent->pushValidationError([
                        'sheet' => 'Variants',
                        'row' => $excelRowNumber,
                        'barcode' => $row['product_barcode'] ?? 'N/A',
                        'errors' => [$e->getMessage()],
                    ]);
                } else {
                    $this->parent->pushResultError([
                        'sheet' => 'Variants',
                        'row' => $excelRowNumber,
                        'barcode' => $row['product_barcode'] ?? 'N/A',
                        'errors' => [$e->getMessage()],
                    ]);
                }
            }
        }
        
        // Process any deferred variants that are now available
        foreach ($this->parent->getDeferredVariants() as $deferredRow) {
            try {
                $barcode = trim((string)$deferredRow['product_barcode']);
                $product = Product::where('barcode', $barcode)->first();
                if ($product) {
                    $this->parent->processVariantDirect($deferredRow, $product);
                } else {
                }
            } catch (\Exception $e) {
            }
        }
        $this->parent->clearDeferredVariants();

    }

    private function isEmptyVariantRow($row): bool
    {
        $fields = ['product_barcode', 'color', 'size', 'price', 'discount', 'quantity'];
        foreach ($fields as $field) {
            if (!empty($row[$field]) && trim((string)$row[$field]) !== '') {
                return false;
            }
        }
        return true;
    }

    private function validateVariantRow($row): array
    {
        $errors = [];

        $barcode = trim((string)($row['product_barcode'] ?? ''));
        if ($barcode === '') {
            $errors[] = 'Product Barcode is required for variant rows.';
            return $errors;
        }

        // Check if product exists in database OR is being imported in this batch
        $product = Product::where('barcode', $barcode)->first();
        $isBeingImported = in_array($barcode, $this->parent->getImportingBarcodes());
        
        if (!$product && !$isBeingImported) {
            $errors[] = "Product with barcode '{$barcode}' not found in database or import.";
            // Continue collecting other errors but processing will be skipped
        }

        // At least one of color or size must be provided
        $colorName = trim((string)($row['color'] ?? ''));
        $sizeName = trim((string)($row['size'] ?? ''));
        
        if ($colorName === '' && $sizeName === '') {
            $errors[] = 'At least one of Color or Size must be provided for a variant.';
        }

        // Validate color if provided
        if ($colorName !== '') {
            if (!$this->parent->findColorByName($colorName)) {
                $errors[] = "Invalid color: '{$colorName}'.";
            }
        }

        // Validate size if provided
        if ($sizeName !== '') {
            if (!$this->parent->findSizeByName($sizeName)) {
                $errors[] = "Invalid size: '{$sizeName}'.";
            }
        }

        // Validate price delta if provided
        if (isset($row['price']) && $row['price'] !== '') {
            if (!is_numeric($row['price'])) {
                $errors[] = 'Price must be a number (positive or negative).';
            }
        }

        // Validate discount if provided
        if (isset($row['discount']) && $row['discount'] !== '') {
            if (!is_numeric($row['discount'])) {
                $errors[] = 'Discount must be a number between 0 and 100.';
            } elseif ((int)$row['discount'] < 0 || (int)$row['discount'] > 100) {
                $errors[] = 'Discount must be between 0 and 100.';
            }
        }

        return $errors;
    }

    private function processVariantRow($row): void
    {
        $barcode = trim((string)$row['product_barcode']);

        $product = Product::where('barcode', $barcode)->first();
        if (!$product) {
            // If this is a product being imported in this batch, defer processing
            if (in_array($barcode, $this->parent->getImportingBarcodes())) {
                // Access parent's deferred variants through parent
                $this->parent->addDeferredVariant($row);
                return;
            }

            // Nothing to process; already reported in errors
            return;
        }

        $this->parent->processVariantDirect($row, $product);
    }
}

/**
 * Handle the optional "Specifications" sheet.
 * This sheet allows adding multiple specifications per product by barcode.
 */
class ProductSpecificationsSheet implements ToCollection, WithHeadingRow
{
    private ProductImport $parent;

    public function __construct(ProductImport $parent)
    {
        $this->parent = $parent;
    }

    public function headingRow(): int
    {
        return 1;
    }

    public function collection(Collection $rows)
    {
        // Group specifications by barcode
        $specsByBarcode = [];

        foreach ($rows as $index => $row) {
            $excelRowNumber = $index + 2;

            // Skip empty rows
            if ($this->isEmptySpecificationRow($row)) {
                continue;
            }

            try {
                $errors = $this->validateSpecificationRow($row);

                if (!empty($errors)) {
                    if ($this->parent->isValidationOnly()) {
                        $this->parent->pushValidationError([
                            'sheet' => 'Specifications',
                            'row' => $excelRowNumber,
                            'barcode' => $row['product_barcode'] ?? 'N/A',
                            'errors' => $errors,
                        ]);

                        $this->parent->pushValidationData([
                            'sheet' => 'Specifications',
                            'barcode' => $row['product_barcode'] ?? 'N/A',
                            'row_data' => $row->toArray(),
                            'is_valid' => false,
                            'errors' => $errors,
                            'warnings' => []
                        ]);
                    } else {
                        $this->parent->pushResultError([
                            'sheet' => 'Specifications',
                            'row' => $excelRowNumber,
                            'barcode' => $row['product_barcode'] ?? 'N/A',
                            'errors' => $errors,
                        ]);
                    }
                    continue;
                }

                if ($this->parent->isValidationOnly()) {
                    $this->parent->pushValidationData([
                        'sheet' => 'Specifications',
                        'barcode' => $row['product_barcode'] ?? 'N/A',
                        'row_data' => $row->toArray(),
                        'is_valid' => true,
                        'errors' => [],
                        'warnings' => []
                    ]);
                    continue;
                }

                // Group by barcode for batch processing
                $barcode = trim((string)$row['product_barcode']);
                if (!isset($specsByBarcode[$barcode])) {
                    $specsByBarcode[$barcode] = [];
                }
                $specsByBarcode[$barcode][] = $row;

            } catch (\Exception $e) {
                if ($this->parent->isValidationOnly()) {
                    $this->parent->pushValidationError([
                        'sheet' => 'Specifications',
                        'row' => $excelRowNumber,
                        'barcode' => $row['product_barcode'] ?? 'N/A',
                        'errors' => [$e->getMessage()],
                    ]);
                } else {
                    $this->parent->pushResultError([
                        'sheet' => 'Specifications',
                        'row' => $excelRowNumber,
                        'barcode' => $row['product_barcode'] ?? 'N/A',
                        'errors' => [$e->getMessage()],
                    ]);
                }
            }
        }

        // Process specifications for each product
        if (!$this->parent->isValidationOnly()) {
            foreach ($specsByBarcode as $barcode => $specRows) {
                $this->processSpecificationsForProduct($barcode, $specRows);
            }
        }
    }

    private function isEmptySpecificationRow($row): bool
    {
        if (empty($row['product_barcode']) || trim((string)$row['product_barcode']) === '') {
            return true;
        }

        $locales = config('app.locales', ['en']);
        foreach ($locales as $locale) {
            $field = "specification_{$locale}";
            if (!empty($row[$field]) && trim((string)$row[$field]) !== '') {
                return false;
            }
        }

        return true;
    }

    private function validateSpecificationRow($row): array
    {
        $errors = [];

        $barcode = trim((string)($row['product_barcode'] ?? ''));
        if ($barcode === '') {
            $errors[] = 'Product Barcode is required for specification rows.';
            return $errors;
        }

        // Check if product exists in database OR is being imported in this batch
        $product = Product::where('barcode', $barcode)->first();
        $isBeingImported = in_array($barcode, $this->parent->getImportingBarcodes());
        
        if (!$product && !$isBeingImported) {
            $errors[] = "Product with barcode '{$barcode}' not found in database or import.";
        }

        // Validate at least one specification is provided
        $locales = config('app.locales', ['en']);
        $hasSpec = false;
        foreach ($locales as $locale) {
            $field = "specification_{$locale}";
            if (!empty($row[$field]) && trim((string)$row[$field]) !== '') {
                $hasSpec = true;
                break;
            }
        }

        if (!$hasSpec) {
            $errors[] = 'At least one specification must be provided.';
        }

        return $errors;
    }

    private function processSpecificationsForProduct(string $barcode, array $specRows): void
    {
        $product = Product::where('barcode', $barcode)->first();
        if (!$product) {
            return;
        }

        // Delete existing specifications for this product
        ProductSpecification::where('product_id', $product->id)->delete();

        // Create new specifications from rows
        $locales = config('app.locales', ['en']);

        foreach ($specRows as $row) {
            $specificationsData = [];

            foreach ($locales as $locale) {
                $field = "specification_{$locale}";
                $value = trim((string)($row[$field] ?? ''));
                if ($value !== '') {
                    $specificationsData[$locale] = $value;
                }
            }

            if (!empty($specificationsData)) {
                ProductSpecification::create([
                    'product_id' => $product->id,
                    'description' => $specificationsData,
                ]);
            }
        }
    }
}
