[program:coverrestlb-worker]
process_name=%(program_name)s_%(process_num)02d
command=php /var/www/coverrestlb/backend/artisan queue:work --sleep=3 --tries=3 --max-time=3600
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=www-data
numprocs=1
redirect_stderr=true
stdout_logfile=/var/www/coverrestlb/backend/storage/logs/worker.log
stdout_logfile_maxbytes=1MB
stdout_logfile_backups=10
stderr_logfile=/var/www/coverrestlb/backend/storage/logs/worker_error.log
stderr_logfile_maxbytes=1MB
stderr_logfile_backups=10